name: texticode_mobile

description: "Texticode - Sistema de gestión textil (versión móvil)"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.2.0

  # Login con Google
  google_sign_in: ^6.2.1

  # Navegación con rutas nombradas / declarativas
  go_router: ^14.8.1

  # Generación de archivos PDF
  pdf: ^3.12.0

  # Impresión de archivos PDF
  printing: ^5.14.3

  url_launcher: ^6.3.1
  path_provider: ^2.1.4
  share_plus: ^10.0.0
  flutter_secure_storage: ^9.2.2

  # Generación de archivos Excel
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/